[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  port = 8888
  targetPort = 5173
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 